module: "Memo"
skip_undocumented: true
xcodebuild_arguments: 
    - "-workspace"
    - "Pocket Note.xcworkspace"
    - "-scheme"
    - "Memo"
min_acl: "private"
author: "Mary Alexis Solis"
theme: "fullwidth"

