module: "Memo"
skip_undocumented: true
xcodebuild_arguments: 
    - "-workspace"
    - "Pocket Note.xcworkspace"
    - "-scheme"
    - "Memo"
min_acl: "private"
author: "Mary Alexis Solis"
theme: "fullwidth"

custom_categories:
    - name: Realm Models
      children:
        - Note
        - Notebook
    - name: View Controllers
      children: 
        - PNCreateNoteViewController
        - PNLoginViewController
        - PNMoveNoteViewController
        - PNNotebooksListViewController
        - PNNotesFeedViewController
        - PNRegistrationViewController
        - PNSideMenuViewController
    - name: Custom Views
      children:
        - PNCreateNoteView
        - PNLoginView
        - PNNotebooksListView
        - PNNotesFeedView
        - PNRegistrationView
        - PNSideMenuView
        - PNNotebooksListTableViewCell
        - PNNotesFeedTableViewCell
    - name: Interactors
      children:
        - PNCreateNotebookInteractor
        - PNNotesEditNotebookInteractor
        - PNNotesTableViewInteractor
        - PNCreateNoteInteractor
        - PNDeleteNotebookInteractor
        - PNLoginInteractor
        - PNRegistrationInteractor
        - PNDeleteNoteInteractor
        - PNSearchNoteInteractor
    - name: Observers
      children:
        - PNDeleteNotebookObserver
        - PNExistingUserErrorObserver
        - PNInvalidLoginErrorObserver
        - PNNoNetworkObserver
    - name: Operations 
      children:
        - PNCreateNoteOperation
        - PNCreateNotebookOperation
        - PNDeleteNoteOperation
        - PNDeleteNotebookOperation
        - PNFetchNoteOperation
        - PNLoginUserOperation
        - PNLogoutUserOperation
        - PNNetworkAvailabilityOperation